include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    always_use_package_imports: false
    prefer_relative_imports: true
